@startuml EVAX_Startup_UseCase

!define ICONURL https://www.plantuml.com/gsoc-sv-2022-icons
!define ICON(size) <img:ICONURL/size>

!define USER actor ICON(16x16)

actor User as User

rectangle EVAX {
  usecase "Login/Register" as LoginRegister
  usecase "Account Management" as AccountManagement
  usecase "Get Vaccination Details" as GetVaccinationDetails
  usecase "Notification for Upcoming Vaccination" as NotificationUpcoming
  usecase "Notification for Completed Vaccination" as NotificationCompleted
  usecase "Vaccination Certificate" as VaccinationCertificate
  usecase "Get Vaccination History" as GetVaccinationHistory
  usecase "Reschedule Vaccination Date" as RescheduleVaccination
  usecase "Request Change of Vaccination Type" as RequestChange
  usecase "Notify User on Date Change" as NotifyDateChange
}

User --> LoginRegister : Requests
LoginRegister --> AccountManagement
LoginRegister --> GetVaccinationDetails
LoginRegister --> NotificationUpcoming
LoginRegister --> NotificationCompleted
LoginRegister --> VaccinationCertificate
GetVaccinationDetails --> GetVaccinationHistory
AccountManagement --> RescheduleVaccination
AccountManagement --> RequestChange
RescheduleVaccination --> NotifyDateChange

@enduml
